/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ScoutsRouteImport } from './routes/scouts'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsIdRouteImport } from './routes/markets.$id'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsRoute = ScoutsRouteImport.update({
  id: '/scouts',
  path: '/scouts',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIdRoute = MarketsIdRouteImport.update({
  id: '/markets/$id',
  path: '/markets/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/scouts': typeof ScoutsRoute
  '/wallet': typeof WalletRoute
  '/markets/$id': typeof MarketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/scouts': typeof ScoutsRoute
  '/wallet': typeof WalletRoute
  '/markets/$id': typeof MarketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/rewards': typeof RewardsRoute
  '/scouts': typeof ScoutsRoute
  '/wallet': typeof WalletRoute
  '/markets/$id': typeof MarketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/profile'
    | '/report'
    | '/rewards'
    | '/scouts'
    | '/wallet'
    | '/markets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/profile'
    | '/report'
    | '/rewards'
    | '/scouts'
    | '/wallet'
    | '/markets/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/profile'
    | '/report'
    | '/rewards'
    | '/scouts'
    | '/wallet'
    | '/markets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  RewardsRoute: typeof RewardsRoute
  ScoutsRoute: typeof ScoutsRoute
  WalletRoute: typeof WalletRoute
  MarketsIdRoute: typeof MarketsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts': {
      id: '/scouts'
      path: '/scouts'
      fullPath: '/scouts'
      preLoaderRoute: typeof ScoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$id': {
      id: '/markets/$id'
      path: '/markets/$id'
      fullPath: '/markets/$id'
      preLoaderRoute: typeof MarketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  RewardsRoute: RewardsRoute,
  ScoutsRoute: ScoutsRoute,
  WalletRoute: WalletRoute,
  MarketsIdRoute: MarketsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
